local SignalConst = {
    SIGNAL_TOWER_ADD = "SIGNAL_TOWER_ADD",
    SIGNAL_TOWER_REMOVE = "SIGNAL_TOWER_REMOVE",
    SIGNAL_MONSTER_DIE = "SIGNAL_MONSTER_DIE",
    SIGNAL_PLAYER_UPDATE_COIN = "SIGNAL_PLAYER_UPDATE_COIN",
    SIGNAL_UPDATE_SKILL = "SIGNAL_UPDATE_SKILL",
    SIGNAL_UPDATE_ITEM = "SIGNAL_UPDATE_ITEM",
    SIGNAL_STAGE_PASS = "SIGNAL_STAGE_PASS",
    SIGNAL_GAME_TIME_REFRESH = "SIGNAL_GAME_TIME_REFRESH",
    SIGNAL_HEROSHOP_LV_UP = "SIGNAL_HEROSHOP_LV_UP"
}

return SignalConst
